# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: prettier
        run: |
          yarn --frozen-lockfile
          yarn prettier
      - name: release
        run: |
          # hack for get version number
          yarn version --new-version "${GITHUB_REF:11}" --no-git-tag-version
  publish-npm:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - name: version number
        run: |
          # hack for get version number
          yarn version --new-version "${GITHUB_REF:11}" --no-git-tag-version
      - run: yarn --frozen-lockfile
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  publish-gpr:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@kkiyama117'
      - name: version number
        run: |
          # hack for get version number
          yarn version --new-version "${GITHUB_REF:11}" --no-git-tag-version
      - run: yarn --frozen-lockfile
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
